_target_: skactiveml.classifier.multiannotator.AnnotMixClassifier
_convert_: all
alpha: 0.5
sample_embed_dim: 1
annotator_embed_dim: 32
hidden_dim: 128
n_hidden_layers: 1
hidden_dropout: 0.1
eta: 0.9
sample_dtype: float32