_target_: skactiveml.classifier.multiannotator.AnnotMixClassifier
_convert_: all
alpha: 0.5
sample_embed_dim: 8
annotator_embed_dim: 8
hidden_dim: null
n_hidden_layers: 1
hidden_dropout: 0.0
eta: 0.9
sample_dtype: float32