_target_: src.dataset.HFDatasetSpec
source: ethz/food101
source_kind: hub_or_local_script
cache_dir: ${paths.dataset_cache_dir}
train_splits: [train]
test_split: validation
x_key: image
y_key: label
z_key: null
trust_remote_code: false
