types:
  - _target_: src.dataset.AnnotatorTypeConfig
    name: expert
    proportion: 0.2
    q_mean: 0.80
    q_std: 0.03
    s_mean: 120
    s_std: 0.18
    kappa_mean: 120
    kappa_std: 0.18
    difficulty_beta_mean: 0.90
    difficulty_beta_std: 0.15

  - _target_: src.dataset.AnnotatorTypeConfig
    name: competent
    proportion: 0.4
    q_mean: 0.65
    q_std: 0.05
    s_mean: 70
    s_std: 0.25
    kappa_mean: 70
    kappa_std: 0.25
    difficulty_beta_mean: 1.60
    difficulty_beta_std: 0.20

  - _target_: src.dataset.AnnotatorTypeConfig
    name: novice
    proportion: 0.20
    q_mean: 0.50
    q_std: 0.08
    s_mean: 30
    s_std: 0.35
    kappa_mean: 30
    kappa_std: 0.35
    difficulty_beta_mean: 2.60
    difficulty_beta_std: 0.25

  - _target_: src.dataset.AnnotatorTypeConfig
    name: spammer_uniform
    proportion: 0.10
    spammer_mode: uniform

  - _target_: src.dataset.AnnotatorTypeConfig
    name: single_class
    proportion: 0.10
    spammer_mode: uniform
