defaults:
  - al: dopanim
  - classifier: annot_mix
  - paths: default
  - dataset: dopanim
  - embedder@classification_embedder: clip
  - embedder@simulation_embedder: null
  - pipeline: default
  - simulation: null
  - module: mlp
  - training: default
  - scheduler: step_ratio_1
  - sample@sample.init: typi_clust
  - sample@sample.actual: falcun
  - scorer@scorer.init: random
  - scorer@scorer.actual: random
  - assigner@assigner.init: quota_sample
  - assigner@assigner.actual: greedy_sample
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
experiment_name: "test"
results_path: ${paths.results_path}
device: "cuda"
missing_label: -1
exit_after_simulation: False
seed: 0
hydra:
  run:
    dir: .
  output_subdir: null
