defaults:
  - al: dermamnist7
  - classifier: annot_mix
  - paths: default
  - dataset: dermamnist7
  - embedder@classification_embedder: dinov2
  - embedder@simulation_embedder: clip
  - pipeline: default
  - simulation: dermamnist7
  - module: mlp
  - training: default
  - scheduler: step_ratio_2_1
  - sample@sample.init: typi_clust
  - sample@sample.actual: margin
  - scorer@scorer.init: random
  - scorer@scorer.actual: beta
  - assigner@assigner.init: quota_sample
  - assigner@assigner.actual: greedy_sample
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
experiment_name: "new"
results_path: ${paths.results_path}
device: "cuda"
missing_label: -1
exit_after_simulation: True
seed: 4
hydra:
  run:
    dir: .
  output_subdir: null
