_target_: src.scorer.BetaModelPairScorer
prior: [1.0, 0.1]
gamma: "mean_gamma"
gamma_scope: "global"
weights_type: "entropy"
representation: "input"
normalize_embeddings: false
use_ess: false
random_state: ${seed}
