_target_: src.scorer.IGKernelChannelPairScorer
accuracy_mean: 0.9
accuracy_strength: 10.0
gamma_x: "median"
gamma_a: "median"
use_annotator_embeddings: false
channel_label_dirichlet_strength: 1.0
channel_variant: "channel"
use_ess_beta: true
tau_beta: 1.0
use_ess_label_dirichlet: true
tau_label_dirichlet: 1.0
top_m: null
n_theta_samples: 1
sample_label_dirichlet: true
